image: node:5.10.0

before_script:
  - apt-get -qq update

cache:
  paths:
  - node_modules/

all_tests:
  script:
   - npm install
   - npm test

production:
  type: deploy
  script:
    - wget http://production.cf.rubygems.org/rubygems/rubygems-2.6.6.tgz
    - tar xvf rubygems*
    - cd rubygems-2.6.6
    - apt-get update -qy
    - apt-get install -y ruby-full
    - ruby setup.rb
    - gem install dpl
    - dpl --provider=heroku --app=leituradebolso --api-key=$HEROKU_PRODUCTION_API_KEY

  only:
  - master
