image: ruby:2.2

before_script:
  - apt-get -qq update
  - curl -sL https://deb.nodesource.com/setup_5.10.0 | sudo -E bash -
  - apt-get install -y nodejs
  - apt-get update


cache:
  paths:
  - node_modules/

all_tests:
  script:
   - npm install
   - npm test

production:
  type: deploy
  script:
    - gem install dpl
    - dpl --provider=heroku --app=leituradebolso --api-key=$HEROKU_PRODUCTION_API_KEY

  only:
  - master
