image: node:5.10.0

before_script:
  - apt-get -qq update

cache:
  paths:
  - node_modules/

all_tests:
  script:
   - npm install
   - npm test

production:
  type: deploy
  script:
  - echo "Y" | apt-get install ruby ruby-dev
  - echo "Y" | apt-get install ruby-dev
  - echo "Y" | libcurl4-openssl-dev make
  - gem install dpl
  - dpl --provider=heroku --app=leituradebolso --api-key=$HEROKU_PRODUCTION_API_KEY

  only:
  - master
