image: node:5.10.0

cache:
  paths:
  - node_modules/

all_tests:
  script:
   - npm install
   - npm test

production:
  type: deploy
  script:
  - apt-get update
  - apt-get update -yq
  - apt-get install -y ruby-dev
  - gem install dpl
  - dpl --provider=heroku --app=leituradebolso --api-key=$HEROKU_PRODUCTION_API_KEY

  only:
  - master
